# Generated by Django 4.0.6 on 2022-07-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infohuman',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
